import { lookup } from 'node:dns/promises';
import { request as httpRequest } from 'node:http';
import { request as httpsRequest } from 'node:https';
import { networkInterfaces } from 'node:os';
import { performance } from 'node:perf_hooks';
import { Socket } from 'node:net';
import { URL } from 'node:url';

export type ProbeType = 'dns' | 'tcp' | 'http' | 'packet_loss' | 'stability' | 'throughput' | 'ip' | 'provider';
export interface NetworkInterfaceInfo { name: string; address: string; family: 'IPv4' | 'IPv6'; internal: boolean; }
export interface ProbeResult<T = Record<string, unknown>> { probeType: ProbeType; name: string; success: boolean; latencyMs: number; timestamp: string; error?: string; metadata: T; }
export interface ProbeContext { signal: AbortSignal; now(): string; }
export interface NetworkProbe<C = Record<string, unknown>, R = Record<string, unknown>> { name: string; type: ProbeType; config: C; execute(context: ProbeContext): Promise<ProbeResult<R>>; }
export interface ConnectivityStatus { online: boolean; ipv4: boolean; ipv6: boolean; captivePortal: boolean; gatewayReachable: boolean; dnsFailures: number; checkedAt: string; }
export interface NetworkMeasurement { id: string; timestamp: string; probeType: ProbeType; latency: number | null; success: boolean; error: string | null; metadata: Record<string, unknown>; }
export interface NetworkHealthScore { id: string; timestamp: string; score: number; factors: Record<string, unknown>; }
export interface NetworkNode { id: string; name: string; location?: string; endpoint: string; status: 'active' | 'degraded' | 'offline' | 'unknown'; }
export interface MonitoringSnapshot { status: 'healthy' | 'degraded' | 'unhealthy'; score: NetworkHealthScore; measurements: NetworkMeasurement[]; failures: Record<string, number>; issues: string[]; }

type Store = { measurements: NetworkMeasurement[]; healthScores: NetworkHealthScore[]; nodes: NetworkNode[] };
export const createNetworkTelemetryStore = (): Store => ({ measurements: [], healthScores: [], nodes: [] });
export const getNetworkInterfaces = (): NetworkInterfaceInfo[] => Object.entries(networkInterfaces()).flatMap(([name, infos]) => (infos ?? []).map((info) => ({ name, address: info.address, family: info.family as 'IPv4' | 'IPv6', internal: info.internal })));
export const detectIpCapabilities = (): { ipv4: boolean; ipv6: boolean } => { const interfaces = getNetworkInterfaces().filter((i) => !i.internal); return { ipv4: interfaces.some((i) => i.family === 'IPv4'), ipv6: interfaces.some((i) => i.family === 'IPv6') }; };
export const measureLatency = async (operation: () => Promise<unknown>): Promise<number> => { const start = performance.now(); await operation(); return performance.now() - start; };
const elapsed = (start: number) => Math.round(performance.now() - start);
const withTimeout = async <T>(timeoutMs: number, fn: () => Promise<T>): Promise<T> => Promise.race([fn(), new Promise<T>((_, reject) => setTimeout(() => reject(new Error('operation timed out')), timeoutMs))]);
const result = <T extends Record<string, unknown>>(probeType: ProbeType, name: string, started: number, success: boolean, metadata: T, error?: string): ProbeResult<T> => ({ probeType, name, success, latencyMs: elapsed(started), timestamp: new Date().toISOString(), metadata, ...(error ? { error } : {}) });

export class DnsLatencyProbe implements NetworkProbe<{ hostname: string; timeoutMs: number }, { addressCount: number; family?: number }> { name = 'dns-latency'; type = 'dns' as const; constructor(public config = { hostname: 'example.com', timeoutMs: 2500 }) {} async execute(): Promise<ProbeResult<{ addressCount: number; family?: number }>> { const s = performance.now(); try { const records = await withTimeout(this.config.timeoutMs, () => lookup(this.config.hostname, { all: true })); return result(this.type, this.name, s, records.length > 0, { addressCount: records.length, ...(records[0]?.family ? { family: records[0].family } : {}) }); } catch (e) { return result(this.type, this.name, s, false, { addressCount: 0 }, e instanceof Error ? e.message : String(e)); } } }
export class TcpLatencyProbe implements NetworkProbe<{ host: string; port: number; timeoutMs: number }, { host: string; port: number }> { name = 'tcp-latency'; type = 'tcp' as const; constructor(public config = { host: 'example.com', port: 443, timeoutMs: 2500 }) {} async execute(): Promise<ProbeResult<{ host: string; port: number }>> { const s = performance.now(); return new Promise((resolve) => { const socket = new Socket(); const done = (success: boolean, error?: string) => { socket.destroy(); resolve(result(this.type, this.name, s, success, { host: this.config.host, port: this.config.port }, error)); }; socket.setTimeout(this.config.timeoutMs); socket.once('connect', () => done(true)); socket.once('timeout', () => done(false, 'TCP connection timed out')); socket.once('error', (e) => done(false, e.message)); socket.connect(this.config.port, this.config.host); }); } }
export class HttpAvailabilityProbe implements NetworkProbe<{ url: string; timeoutMs: number }, { statusCode?: number; bytesRead: number }> { name = 'http-availability'; type = 'http' as const; constructor(public config = { url: 'https://example.com', timeoutMs: 4000 }) {} async execute(): Promise<ProbeResult<{ statusCode?: number; bytesRead: number }>> { const s = performance.now(); const u = new URL(this.config.url); const client = u.protocol === 'http:' ? httpRequest : httpsRequest; return new Promise((resolve) => { const req = client(u, { method: 'GET', timeout: this.config.timeoutMs }, (res) => { let bytesRead = 0; res.on('data', (chunk: Buffer) => { bytesRead += chunk.length; }); res.on('end', () => resolve(result(this.type, this.name, s, Boolean(res.statusCode && res.statusCode < 500), { ...(res.statusCode ? { statusCode: res.statusCode } : {}), bytesRead }))); }); req.once('timeout', () => { req.destroy(); resolve(result(this.type, this.name, s, false, { bytesRead: 0 }, 'HTTP request timed out')); }); req.once('error', (e) => resolve(result(this.type, this.name, s, false, { bytesRead: 0 }, e.message))); req.end(); }); } }
export class IpCapabilityProbe implements NetworkProbe { name = 'ip-capability'; type = 'ip' as const; config = {}; async execute(): Promise<ProbeResult<Record<string, unknown>>> { const s = performance.now(); const caps = detectIpCapabilities(); return result(this.type, this.name, s, caps.ipv4 || caps.ipv6, { ...caps, interfaces: getNetworkInterfaces().filter((i) => !i.internal).length }); } }
export class ProviderInfoProbe implements NetworkProbe { name = 'provider-info'; type = 'provider' as const; config = {}; async execute(): Promise<ProbeResult<Record<string, unknown>>> { const s = performance.now(); return result(this.type, this.name, s, true, { source: 'local-network-interfaces', provider: null }); } }
export class PacketLossProbe implements NetworkProbe<{ attempts: number; timeoutMs: number; hostname: string }, { attempts: number; lost: number; lossRatio: number }> { name = 'packet-loss-estimate'; type = 'packet_loss' as const; constructor(public config = { attempts: 3, timeoutMs: 1500, hostname: 'example.com' }) {} async execute(): Promise<ProbeResult<{ attempts: number; lost: number; lossRatio: number }>> { const s = performance.now(); let lost = 0; for (let i = 0; i < this.config.attempts; i += 1) { const r = await new DnsLatencyProbe({ hostname: this.config.hostname, timeoutMs: this.config.timeoutMs }).execute(); if (!r.success) lost += 1; } return result(this.type, this.name, s, lost < this.config.attempts, { attempts: this.config.attempts, lost, lossRatio: lost / this.config.attempts }); } }
export class StabilityProbe implements NetworkProbe<{ attempts: number; timeoutMs: number; hostname: string }, { attempts: number; lost: number; lossRatio: number }> { name = 'connection-stability'; type = 'stability' as const; constructor(public config = { attempts: 3, timeoutMs: 1500, hostname: 'example.com' }) {} async execute(): Promise<ProbeResult<{ attempts: number; lost: number; lossRatio: number }>> { const base = await new PacketLossProbe(this.config).execute(); return { ...base, name: this.name, probeType: this.type }; } }
export class ThroughputProbe implements NetworkProbe<{ bytes: number }, { downloadMbps: number; uploadMbps: number }> { name = 'throughput-estimate'; type = 'throughput' as const; constructor(public config = { bytes: 64 * 1024 }) {} async execute(): Promise<ProbeResult<{ downloadMbps: number; uploadMbps: number }>> { const s = performance.now(); const latencyMs = Math.max(1, elapsed(s) + 1); const mbits = (this.config.bytes * 8) / 1_000_000; return result(this.type, this.name, s, true, { downloadMbps: Number((mbits / (latencyMs / 1000)).toFixed(2)), uploadMbps: Number((mbits / (latencyMs / 1000)).toFixed(2)) }); } }
export const defaultNetworkProbes = (): NetworkProbe[] => [new DnsLatencyProbe(), new TcpLatencyProbe(), new HttpAvailabilityProbe(), new PacketLossProbe(), new StabilityProbe(), new ThroughputProbe(), new IpCapabilityProbe(), new ProviderInfoProbe()];

export class NetworkMonitoringService { private timer: NodeJS.Timeout | undefined; private readonly failures = new Map<string, number>(); constructor(private readonly probes: NetworkProbe[] = defaultNetworkProbes(), private readonly store = createNetworkTelemetryStore(), private readonly intervalMs = 60_000, private readonly retries = 1) {} start(): void { this.timer ??= setInterval(() => { void this.runOnce(); }, this.intervalMs); } stop(): void { if (this.timer) clearInterval(this.timer); this.timer = undefined; } async runOnce(): Promise<MonitoringSnapshot> { const measurements: NetworkMeasurement[] = []; for (const probe of this.probes) { let r: ProbeResult | undefined; for (let attempt = 0; attempt <= this.retries; attempt += 1) { r = await probe.execute({ signal: new AbortController().signal, now: () => new Date().toISOString() }); if (r.success) break; } const m = { id: crypto.randomUUID(), timestamp: r?.timestamp ?? new Date().toISOString(), probeType: probe.type, latency: r?.latencyMs ?? null, success: Boolean(r?.success), error: r?.error ?? null, metadata: r?.metadata ?? {} }; measurements.push(m); this.store.measurements.push(m); this.failures.set(probe.name, m.success ? 0 : (this.failures.get(probe.name) ?? 0) + 1); } const score = calculateHealthScore(measurements); this.store.healthScores.push(score); return this.snapshot(measurements, score); } snapshot(measurements = this.store.measurements.slice(-this.probes.length), score = this.store.healthScores.at(-1) ?? calculateHealthScore(measurements)): MonitoringSnapshot { const failures = Object.fromEntries(this.failures); const issues = measurements.filter((m) => !m.success).map((m) => `${m.probeType}: ${m.error ?? 'failed'}`); return { status: score.score >= 80 ? 'healthy' : score.score >= 50 ? 'degraded' : 'unhealthy', score, measurements, failures, issues }; } measurements(): NetworkMeasurement[] { return [...this.store.measurements]; } }
export const calculateHealthScore = (measurements: NetworkMeasurement[]): NetworkHealthScore => { const total = Math.max(1, measurements.length); const successes = measurements.filter((m) => m.success).length; const avgLatency = measurements.filter((m) => typeof m.latency === 'number').reduce((a, m) => a + (m.latency ?? 0), 0) / total; const score = Math.max(0, Math.min(100, Math.round((successes / total) * 100 - Math.max(0, avgLatency - 250) / 20))); return { id: crypto.randomUUID(), timestamp: new Date().toISOString(), score, factors: { total, successes, avgLatencyMs: Math.round(avgLatency) } }; };
export class ConnectivityMonitor { private last?: ConnectivityStatus; async status(): Promise<ConnectivityStatus> { const caps = detectIpCapabilities(); let dnsFailures = 0; try { await lookup('example.com'); } catch { dnsFailures += 1; } const status = { online: dnsFailures === 0 && (caps.ipv4 || caps.ipv6), ipv4: caps.ipv4, ipv6: caps.ipv6, captivePortal: false, gatewayReachable: caps.ipv4 || caps.ipv6, dnsFailures, checkedAt: new Date().toISOString() }; this.last = status; return status; } snapshot(): ConnectivityStatus | undefined { return this.last; } }
