import { appendFileSync, mkdirSync, renameSync, statSync, existsSync } from 'node:fs';
import { dirname } from 'node:path';

export type LogLevel = 'debug' | 'info' | 'warn' | 'error';
export interface LogRecord { timestamp: string; level: LogLevel; message: string; traceId?: string; requestId?: string; context?: Record<string, unknown>; }
export interface Transport { write(record: LogRecord): void; }
export interface LoggerOptions { json?: boolean; color?: boolean; rotation?: { maxBytes: number; maxFiles: number }; }
const colors: Record<LogLevel, string> = { debug: '\u001B[36m', info: '\u001B[32m', warn: '\u001B[33m', error: '\u001B[31m' };
export class ConsoleTransport implements Transport { constructor(private readonly options: LoggerOptions = { json: true }) {} write(record: LogRecord): void { const line = this.options.json === false ? `${record.timestamp} ${record.level.toUpperCase()} ${record.message} ${record.context ? JSON.stringify(record.context) : ''}` : JSON.stringify(record); const output = this.options.color ? `${colors[record.level]}${line}\u001B[0m` : line; record.level === 'error' ? console.error(output) : console.log(output); } }
export class FileTransport implements Transport { constructor(private readonly filePath: string, private readonly rotation?: { maxBytes: number; maxFiles: number }) { mkdirSync(dirname(filePath), { recursive: true }); } write(record: LogRecord): void { this.rotateIfNeeded(); appendFileSync(this.filePath, `${JSON.stringify(record)}\n`); } private rotateIfNeeded(): void { if (!this.rotation || !existsSync(this.filePath)) return; if (statSync(this.filePath).size < this.rotation.maxBytes) return; for (let i = this.rotation.maxFiles - 1; i >= 1; i -= 1) { const from = `${this.filePath}.${i}`; const to = `${this.filePath}.${i + 1}`; if (existsSync(from)) renameSync(from, to); } renameSync(this.filePath, `${this.filePath}.1`); } }
export class Logger { constructor(private readonly transports: Transport[] = [new ConsoleTransport()], private readonly minLevel: LogLevel = 'info', private readonly baseContext: Record<string, unknown> = {}) {} private rank: Record<LogLevel, number> = { debug: 10, info: 20, warn: 30, error: 40 }; child(context: Record<string, unknown>): Logger { return new Logger(this.transports, this.minLevel, { ...this.baseContext, ...context }); } log(level: LogLevel, message: string, context?: Record<string, unknown>): void { if (this.rank[level] < this.rank[this.minLevel]) return; const merged = { ...this.baseContext, ...context }; const record: LogRecord = { timestamp: new Date().toISOString(), level, message, ...(typeof merged.traceId === 'string' ? { traceId: merged.traceId } : {}), ...(typeof merged.requestId === 'string' ? { requestId: merged.requestId } : {}), ...(Object.keys(merged).length ? { context: merged } : {}) }; this.transports.forEach((t) => t.write(record)); } debug(m: string, c?: Record<string, unknown>): void { this.log('debug', m, c); } info(m: string, c?: Record<string, unknown>): void { this.log('info', m, c); } warn(m: string, c?: Record<string, unknown>): void { this.log('warn', m, c); } error(m: string, c?: Record<string, unknown>): void { this.log('error', m, c); } }
export const createLogger = (level: LogLevel = 'info', options: LoggerOptions = { json: true }): Logger => new Logger([new ConsoleTransport(options)], level);
