export type StarlinkResourceId =
  | 'starlink-reverse-egress'
  | 'javidnet'
  | 'javid-mask'
  | 'getastatic'
  | 'egret'
  | 'nasnet-connect'
  | 'starlinux-pi-starlink'
  | 'gbrandt-pi-starlink'
  | 'raspberry-gateway'
  | 'realink-setalink';

export type StarlinkResourceKind = 'architecture' | 'self-hosted' | 'service' | 'software';
export type StarlinkResourceLifecycle = 'active' | 'needs-verification' | 'unverified';
export type StarlinkTunnelProtocol = 'wireguard' | 'openvpn' | 'vless' | 'vmess' | 'reality' | 'shadowsocks' | 'trojan' | 'socks5' | 'zerotier' | 'l2tp' | 'sstp' | 'ikev2' | 'pptp' | 'ssh' | 'http-proxy';
export type StarlinkResourceCapability =
  | 'reverse-egress'
  | 'public-ip'
  | 'inbound-access'
  | 'outbound-egress'
  | 'vpn-gateway'
  | 'proxy-gateway'
  | 'mesh'
  | 'split-tunneling'
  | 'failover'
  | 'load-balancing'
  | 'ipv6'
  | 'ddns'
  | 'remote-access'
  | 'mikrotik'
  | 'router-gateway';

export interface StarlinkResourceSource {
  url: string;
  kind: 'github' | 'official-service' | 'official-docs' | 'project-site';
  verifiedAt: string;
}

export interface StarlinkResource {
  id: StarlinkResourceId;
  name: string;
  kind: StarlinkResourceKind;
  lifecycle: StarlinkResourceLifecycle;
  description: string;
  protocols: StarlinkTunnelProtocol[];
  capabilities: StarlinkResourceCapability[];
  freeTier: boolean;
  publicEndpointProvided: boolean;
  requiresUserOwnedStarlink: boolean;
  sources: StarlinkResourceSource[];
  notes: string[];
}

const verifiedAt = '2026-08-31';

export const STARLINK_RESOURCES: readonly StarlinkResource[] = [
  {
    id: 'starlink-reverse-egress',
    name: 'Starlink Reverse Egress',
    kind: 'architecture',
    lifecycle: 'active',
    description: 'Reverse/outside-initiated Starlink egress architecture using a WireGuard tunnel between an Iran-side VPS and a Starlink-connected node.',
    protocols: ['wireguard', 'openvpn', 'vless'],
    capabilities: ['reverse-egress', 'outbound-egress', 'vpn-gateway', 'proxy-gateway', 'failover', 'load-balancing'],
    freeTier: false,
    publicEndpointProvided: false,
    requiresUserOwnedStarlink: true,
    sources: [{ url: 'https://github.com/RezaHarirchian/starlink-reverse-egress', kind: 'github', verifiedAt }],
    notes: ['Architecture only; credentials and live endpoints are never stored in the catalog.', 'Requires a reachable user-controlled Starlink node and a separately managed gateway.'],
  },
  {
    id: 'javidnet',
    name: 'JavidNet',
    kind: 'software',
    lifecycle: 'needs-verification',
    description: 'Open-source mesh architecture with LEAF, HOP and GATEWAY roles and a local SOCKS5 client interface.',
    protocols: ['socks5'],
    capabilities: ['mesh', 'proxy-gateway', 'router-gateway'],
    freeTier: true,
    publicEndpointProvided: false,
    requiresUserOwnedStarlink: true,
    sources: [{ url: 'https://github.com/Iman/javidnet', kind: 'github', verifiedAt }],
    notes: ['The project catalog does not treat the local SOCKS5 listener as a public proxy endpoint.', 'Gateway availability must be discovered at runtime.'],
  },
  {
    id: 'javid-mask',
    name: 'Javid Mask',
    kind: 'architecture',
    lifecycle: 'needs-verification',
    description: 'Privacy/gateway architecture combining Xray-style protocols and WireGuard/VPS routing patterns.',
    protocols: ['vless', 'vmess', 'reality', 'wireguard'],
    capabilities: ['vpn-gateway', 'proxy-gateway', 'outbound-egress', 'remote-access'],
    freeTier: false,
    publicEndpointProvided: false,
    requiresUserOwnedStarlink: true,
    sources: [{ url: 'https://github.com/Iman/javid-mask', kind: 'github', verifiedAt }],
    notes: ['Architecture reference; no public credentials or connection strings are embedded.'],
  },
  {
    id: 'getastatic',
    name: 'GetAStatic Starlink Static IPv4',
    kind: 'service',
    lifecycle: 'active',
    description: 'Managed static public IPv4 delivered to a Starlink-connected device over an outbound WireGuard tunnel.',
    protocols: ['wireguard'],
    capabilities: ['public-ip', 'inbound-access', 'outbound-egress', 'remote-access'],
    freeTier: true,
    publicEndpointProvided: false,
    requiresUserOwnedStarlink: true,
    sources: [{ url: 'https://getastatic.com/starlink-static-ip', kind: 'official-service', verifiedAt }],
    notes: ['Free plan availability and limits are provider-controlled and must be revalidated before provisioning.', 'A live WireGuard configuration is generated by the service and is not part of this repository.'],
  },
  {
    id: 'egret',
    name: 'Egret Starlink Static IPv4',
    kind: 'service',
    lifecycle: 'active',
    description: 'Managed static public IPv4 over WireGuard for Starlink and other CGNAT links.',
    protocols: ['wireguard'],
    capabilities: ['public-ip', 'inbound-access', 'outbound-egress', 'remote-access'],
    freeTier: true,
    publicEndpointProvided: false,
    requiresUserOwnedStarlink: true,
    sources: [{ url: 'https://egret.host/starlink-static-ip', kind: 'official-service', verifiedAt }],
    notes: ['Displayed IP addresses are examples/session state, not reusable public configurations.', 'Live plan limits and endpoints must be fetched from the provider before activation.'],
  },
  {
    id: 'nasnet-connect',
    name: 'NASNET Connect',
    kind: 'software',
    lifecycle: 'active',
    description: 'Open-source Starlink/MikroTik networking project covering VPN services, split routing, remote access and router configuration.',
    protocols: ['wireguard', 'openvpn', 'l2tp', 'pptp', 'sstp', 'ikev2', 'socks5', 'ssh', 'http-proxy', 'zerotier'],
    capabilities: ['vpn-gateway', 'proxy-gateway', 'split-tunneling', 'remote-access', 'mikrotik', 'router-gateway'],
    freeTier: true,
    publicEndpointProvided: false,
    requiresUserOwnedStarlink: true,
    sources: [
      { url: 'https://github.com/nasnet-community/connect', kind: 'github', verifiedAt },
      { url: 'https://connect.starlink4iran.com/', kind: 'project-site', verifiedAt },
    ],
    notes: ['This is a self-hosted/community networking project, not a catalog of public VPN credentials.'],
  },
  {
    id: 'starlinux-pi-starlink',
    name: 'StarlinuX / Pi-Starlink',
    kind: 'self-hosted',
    lifecycle: 'needs-verification',
    description: 'Raspberry Pi/OpenWRT-oriented Starlink gateway approach with IPv6, DDNS and self-hosted VPN capabilities.',
    protocols: ['wireguard', 'openvpn'],
    capabilities: ['vpn-gateway', 'ipv6', 'ddns', 'remote-access', 'router-gateway'],
    freeTier: true,
    publicEndpointProvided: false,
    requiresUserOwnedStarlink: true,
    sources: [{ url: 'https://github.com/davixdedem/Pi-Starlink', kind: 'github', verifiedAt }],
    notes: ['Requires user-owned Starlink connectivity and compatible hardware/software.', 'The project creates a user-owned VPN; it is not a third-party public VPN endpoint.'],
  },
  {
    id: 'gbrandt-pi-starlink',
    name: 'Pi-Starlink',
    kind: 'self-hosted',
    lifecycle: 'needs-verification',
    description: 'Self-hosted Raspberry Pi Starlink gateway pattern using public IPv6 and VPN services.',
    protocols: ['wireguard', 'openvpn'],
    capabilities: ['vpn-gateway', 'ipv6', 'ddns', 'remote-access', 'router-gateway'],
    freeTier: true,
    publicEndpointProvided: false,
    requiresUserOwnedStarlink: true,
    sources: [{ url: 'https://github.com/gbrandt/Pi-Starlink', kind: 'github', verifiedAt }],
    notes: ['Requires Starlink IPv6 connectivity and user-controlled infrastructure.'],
  },
  {
    id: 'raspberry-gateway',
    name: 'Raspberry Gateway',
    kind: 'self-hosted',
    lifecycle: 'needs-verification',
    description: 'Raspberry Pi Starlink gateway pattern with Xray-based proxy protocols and a local SOCKS5 interface.',
    protocols: ['socks5', 'vless', 'vmess', 'shadowsocks', 'trojan'],
    capabilities: ['proxy-gateway', 'router-gateway', 'outbound-egress'],
    freeTier: true,
    publicEndpointProvided: false,
    requiresUserOwnedStarlink: true,
    sources: [{ url: 'https://github.com/d3vilh/raspberry-gateway', kind: 'github', verifiedAt }],
    notes: ['Any sample/default credentials from upstream documentation must be changed before deployment.', 'The catalog intentionally stores no credentials.'],
  },
  {
    id: 'realink-setalink',
    name: 'Realink / Setalink',
    kind: 'service',
    lifecycle: 'needs-verification',
    description: 'Managed VPN service advertised as Starlink-powered, exposing VLESS/Reality/V2Ray access through supported clients.',
    protocols: ['vless', 'reality'],
    capabilities: ['vpn-gateway', 'outbound-egress'],
    freeTier: true,
    publicEndpointProvided: false,
    requiresUserOwnedStarlink: false,
    sources: [{ url: 'https://setalink.no/', kind: 'official-service', verifiedAt }],
    notes: ['Service claims and free quota are provider-controlled and must be revalidated before use.', 'No public connection URI is assumed or stored.'],
  },
] as const;

export function getStarlinkResource(id: StarlinkResourceId): StarlinkResource | undefined {
  return STARLINK_RESOURCES.find((resource) => resource.id === id);
}

export interface StarlinkResourceQuery {
  protocol?: StarlinkTunnelProtocol;
  capability?: StarlinkResourceCapability;
  freeOnly?: boolean;
  publicEndpointOnly?: boolean;
  lifecycle?: StarlinkResourceLifecycle | StarlinkResourceLifecycle[];
  requiresUserOwnedStarlink?: boolean;
}

export function listStarlinkResources(query: StarlinkResourceQuery = {}): StarlinkResource[] {
  const lifecycles = query.lifecycle === undefined ? undefined : Array.isArray(query.lifecycle) ? query.lifecycle : [query.lifecycle];
  return STARLINK_RESOURCES
    .filter((resource) => query.protocol === undefined || resource.protocols.includes(query.protocol))
    .filter((resource) => query.capability === undefined || resource.capabilities.includes(query.capability))
    .filter((resource) => !query.freeOnly || resource.freeTier)
    .filter((resource) => !query.publicEndpointOnly || resource.publicEndpointProvided)
    .filter((resource) => query.requiresUserOwnedStarlink === undefined || resource.requiresUserOwnedStarlink === query.requiresUserOwnedStarlink)
    .filter((resource) => lifecycles === undefined || lifecycles.includes(resource.lifecycle))
    .map((resource) => ({ ...resource, protocols: [...resource.protocols], capabilities: [...resource.capabilities], sources: resource.sources.map((source) => ({ ...source })), notes: [...resource.notes] }));
}
