import { EventEmitter } from 'node:events';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { platform } from 'node:os';

const execFileAsync = promisify(execFile);

export type DnsRecordType = 'A' | 'AAAA' | 'CNAME' | 'TXT' | 'MX' | 'NS';
export interface DnsQuestion { name: string; recordType: DnsRecordType; protocol?: 'udp' | 'tcp' | 'doh' | 'dot'; interfaceName?: string; }
export interface DnsAnswer { name: string; recordType: DnsRecordType; ttl: number; value: string; dnssecValidated?: boolean; }
export interface DnsResolver { resolve(question: DnsQuestion): Promise<DnsAnswer[]>; }
export interface DnsProvider { id: string; name: string; resolvers: DnsResolver[]; addresses?: string[]; privacyScore?: number; securityScore?: number; supportsDnssec?: boolean; protocols?: DnsQuestion['protocol'][]; group?: string; }
export interface DnsHealthSample { providerId: string; healthy: boolean; latencyMs: number; packetLoss: number; timestamp: number; dnssecValid?: boolean; reason?: string; }
export interface DnsHealthCheck { check(provider: DnsProvider): Promise<{ healthy: boolean; latencyMs: number; reason?: string; packetLoss?: number; dnssecValid?: boolean }>; }
export interface DnsBenchmark { run(providers: DnsProvider[], question: DnsQuestion): Promise<Array<{ providerId: string; latencyMs: number; success: boolean }>>; }
export type DecisionStrategy = 'lowest-latency' | 'highest-availability' | 'lowest-packet-loss' | 'balanced' | 'privacy-first' | 'security-first' | 'custom';
export interface ProviderWeights { latency: number; availability: number; packetLoss: number; privacy: number; security: number; stability: number; prediction: number; }
export interface FailoverConfig { failureThreshold: number; recoveryThreshold: number; cooldownMs: number; failback: 'automatic' | 'manual' | 'disabled'; redundantGroups: string[][]; }
export interface DnsEngineConfig { strategy: DecisionStrategy; weights: ProviderWeights; failover: FailoverConfig; minSwitchScoreDelta: number; historyLimit: number; dnssec: { enabled: boolean; requireValidation: boolean; trustAnchors: string[] }; cache: { ttlMs: number; warmDomains: string[] }; }
export interface ProviderScore { provider: DnsProvider; score: number; rank: number; reasons: string[]; prediction: HealthPrediction; }
export interface HealthPrediction { expectedLatencyMs: number; degradationScore: number; failureProbability: number; stabilityTrend: 'improving' | 'stable' | 'degrading'; }
export interface DnsEngineEvent { type: string; providerId?: string; message: string; timestamp: string; metadata?: Record<string, unknown>; }

export const defaultDnsEngineConfig = (): DnsEngineConfig => ({ strategy: 'balanced', weights: { latency: 0.25, availability: 0.25, packetLoss: 0.2, privacy: 0.1, security: 0.1, stability: 0.05, prediction: 0.05 }, failover: { failureThreshold: 2, recoveryThreshold: 2, cooldownMs: 30_000, failback: 'automatic', redundantGroups: [] }, minSwitchScoreDelta: 0.08, historyLimit: 200, dnssec: { enabled: true, requireValidation: false, trustAnchors: [] }, cache: { ttlMs: 300_000, warmDomains: ['example.com'] } });

export class InMemoryDnsCache { private readonly entries = new Map<string, { answers: DnsAnswer[]; expiresAt: number; hits: number }>(); private misses = 0; get(question: DnsQuestion): DnsAnswer[] | undefined { const key = this.key(question); const entry = this.entries.get(key); if (!entry || entry.expiresAt < Date.now()) { this.entries.delete(key); this.misses++; return undefined; } entry.hits++; return entry.answers; } set(question: DnsQuestion, answers: DnsAnswer[], ttlMs: number): void { this.entries.set(this.key(question), { answers, expiresAt: Date.now() + ttlMs, hits: 0 }); } flush(): number { const size = this.entries.size; this.entries.clear(); return size; } expire(): number { let expired = 0; for (const [key, entry] of this.entries) if (entry.expiresAt < Date.now()) { this.entries.delete(key); expired++; } return expired; } stats() { const hits = [...this.entries.values()].reduce((sum, entry) => sum + entry.hits, 0); return { entries: this.entries.size, hits, misses: this.misses, hitRatio: hits / Math.max(1, hits + this.misses) }; } private key(question: DnsQuestion): string { return `${question.name}:${question.recordType}:${question.protocol ?? 'udp'}:${question.interfaceName ?? 'default'}`; } }

export class RuleEngine { constructor(private readonly rules: DnsRule[] = []) {} evaluate(question: DnsQuestion): DnsRule | undefined { return [...this.rules].sort((a, b) => b.priority - a.priority).find((rule) => this.matches(rule, question)); } list(): DnsRule[] { return [...this.rules].sort((a, b) => b.priority - a.priority); } private matches(rule: DnsRule, question: DnsQuestion): boolean { const domain = question.name.toLowerCase(); const value = rule.value.toLowerCase(); if (rule.interfaceName && rule.interfaceName !== question.interfaceName) return false; if (rule.protocol && rule.protocol !== question.protocol) return false; switch (rule.match) { case 'domain': return domain === value; case 'wildcard': return new RegExp(`^${value.replaceAll('.', '\\.').replaceAll('*', '.*')}$`).test(domain); case 'suffix': return domain.endsWith(value); case 'regex': return new RegExp(rule.value).test(question.name); case 'tld': return domain.endsWith(`.${value.replace(/^\./, '')}`); case 'ip-range': case 'cidr': return domain === value; } } }
export interface DnsRule { id: string; priority: number; match: 'domain' | 'wildcard' | 'suffix' | 'regex' | 'tld' | 'ip-range' | 'cidr'; value: string; action: 'force-provider' | 'block' | 'bypass' | 'prefer-provider' | 'fallback-provider' | 'routing-profile'; providerId?: string; profileId?: string; protocol?: DnsQuestion['protocol']; interfaceName?: string; }
export interface RoutingProfile { id: string; name: string; preferredProviders: string[]; timeoutMs: number; retryPolicy: { attempts: number; backoffMs: number }; benchmarkFrequencyMs: number; protocols: DnsQuestion['protocol'][]; inherits?: string; }
export const builtInProfiles: RoutingProfile[] = [
  { id: 'streaming', name: 'Streaming', preferredProviders: [], timeoutMs: 1200, retryPolicy: { attempts: 2, backoffMs: 50 }, benchmarkFrequencyMs: 60_000, protocols: ['udp', 'doh'] },
  { id: 'gaming', name: 'Gaming', preferredProviders: [], timeoutMs: 500, retryPolicy: { attempts: 1, backoffMs: 20 }, benchmarkFrequencyMs: 30_000, protocols: ['udp'] },
  { id: 'development', name: 'Development', preferredProviders: [], timeoutMs: 2000, retryPolicy: { attempts: 2, backoffMs: 100 }, benchmarkFrequencyMs: 120_000, protocols: ['udp', 'tcp', 'doh'] },
  { id: 'privacy', name: 'Privacy', preferredProviders: [], timeoutMs: 1500, retryPolicy: { attempts: 2, backoffMs: 75 }, benchmarkFrequencyMs: 90_000, protocols: ['doh', 'dot'] },
  { id: 'security', name: 'Security', preferredProviders: [], timeoutMs: 1500, retryPolicy: { attempts: 2, backoffMs: 75 }, benchmarkFrequencyMs: 90_000, protocols: ['doh', 'dot'] },
  { id: 'corporate', name: 'Corporate', preferredProviders: [], timeoutMs: 2500, retryPolicy: { attempts: 3, backoffMs: 200 }, benchmarkFrequencyMs: 300_000, protocols: ['udp', 'tcp'] },
];

export class IntelligentDnsEngine extends EventEmitter { private activeProviderId: string | undefined; private lastSwitchAt = 0; private readonly history = new Map<string, DnsHealthSample[]>(); private readonly failureStreak = new Map<string, number>(); private readonly recoveryStreak = new Map<string, number>(); public readonly cache = new InMemoryDnsCache(); public readonly rules: RuleEngine; public readonly events: DnsEngineEvent[] = [];
  constructor(private readonly providers: DnsProvider[], private readonly healthCheck: DnsHealthCheck, private readonly config = defaultDnsEngineConfig(), rules: DnsRule[] = [], public readonly profiles: RoutingProfile[] = builtInProfiles) { super(); this.rules = new RuleEngine(rules); this.activeProviderId = providers[0]?.id; }
  status() { return { activeProviderId: this.activeProviderId, strategy: this.config.strategy, providers: this.rankProviders(), cache: this.cache.stats(), dnssec: { enabled: this.config.dnssec.enabled, trustAnchors: this.config.dnssec.trustAnchors.length }, events: this.events.slice(-50) }; }
  async evaluate(): Promise<ProviderScore[]> { for (const provider of this.providers) await this.recordHealth(provider); const ranked = this.rankProviders(); const best = ranked[0]; if (best) this.maybeSwitch(best); return ranked; }
  async resolve(question: DnsQuestion): Promise<DnsAnswer[]> { const rule = this.rules.evaluate(question); if (rule?.action === 'block') throw new Error(`DNS query blocked by rule ${rule.id}`); const cached = this.cache.get(question); if (cached) return cached; const provider = this.selectProviderForRule(rule) ?? this.providers.find((candidate) => candidate.id === this.activeProviderId) ?? this.providers[0]; if (!provider) throw new Error('No DNS providers configured'); const answers = await provider.resolvers[0]?.resolve(question); if (!answers) throw new Error(`Provider ${provider.id} has no resolver`); this.cache.set(question, answers, this.config.cache.ttlMs); this.recordEvent('routing.decision', provider.id, `Resolved ${question.name} with ${provider.name}`, { ruleId: rule?.id }); return answers; }
  selectProvider(providerId: string): void { const provider = this.providers.find((candidate) => candidate.id === providerId); if (!provider) throw new Error(`Unknown provider ${providerId}`); this.activeProviderId = providerId; this.lastSwitchAt = Date.now(); this.recordEvent('provider.manual_select', providerId, `Selected ${provider.name}`); }
  private async recordHealth(provider: DnsProvider): Promise<void> { const result = await this.healthCheck.check(provider); const sample: DnsHealthSample = { providerId: provider.id, healthy: result.healthy, latencyMs: result.latencyMs, packetLoss: result.packetLoss ?? (result.healthy ? 0 : 1), timestamp: Date.now(), ...(result.dnssecValid === undefined ? {} : { dnssecValid: result.dnssecValid }), ...(result.reason === undefined ? {} : { reason: result.reason }) }; const list = [...(this.history.get(provider.id) ?? []), sample].slice(-this.config.historyLimit); this.history.set(provider.id, list); this.failureStreak.set(provider.id, result.healthy ? 0 : (this.failureStreak.get(provider.id) ?? 0) + 1); this.recoveryStreak.set(provider.id, result.healthy ? (this.recoveryStreak.get(provider.id) ?? 0) + 1 : 0); if (!result.healthy && (this.failureStreak.get(provider.id) ?? 0) >= this.config.failover.failureThreshold) this.recordEvent('failover.detected', provider.id, result.reason ?? 'Failure threshold exceeded'); }
  rankProviders(): ProviderScore[] { return this.providers.map((provider) => this.score(provider)).sort((a, b) => b.score - a.score).map((score, index) => ({ ...score, rank: index + 1 })); }
  private score(provider: DnsProvider): ProviderScore { const samples = this.history.get(provider.id) ?? []; const recent = samples.slice(-20); const availability = recent.length ? recent.filter((s) => s.healthy).length / recent.length : 1; const avgLatency = recent.length ? recent.reduce((s, x) => s + x.latencyMs, 0) / recent.length : 100; const packetLoss = recent.length ? recent.reduce((s, x) => s + x.packetLoss, 0) / recent.length : 0; const prediction = this.predict(provider.id); const weights = this.strategyWeights(); const score = (1 / Math.max(1, avgLatency)) * 100 * weights.latency + availability * weights.availability + (1 - packetLoss) * weights.packetLoss + (provider.privacyScore ?? 0.5) * weights.privacy + (provider.securityScore ?? 0.5) * weights.security + (1 - prediction.degradationScore) * weights.prediction + (prediction.stabilityTrend === 'stable' ? 1 : 0.5) * weights.stability; return { provider, score, rank: 0, prediction, reasons: [`availability=${availability.toFixed(2)}`, `latency=${avgLatency.toFixed(1)}ms`, `loss=${packetLoss.toFixed(2)}`] }; }
  private strategyWeights(): ProviderWeights { const base = this.config.weights; if (this.config.strategy === 'lowest-latency') return { ...base, latency: 0.7 }; if (this.config.strategy === 'highest-availability') return { ...base, availability: 0.7 }; if (this.config.strategy === 'lowest-packet-loss') return { ...base, packetLoss: 0.7 }; if (this.config.strategy === 'privacy-first') return { ...base, privacy: 0.55 }; if (this.config.strategy === 'security-first') return { ...base, security: 0.55 }; return base; }
  private predict(providerId: string): HealthPrediction { const samples = this.history.get(providerId) ?? []; const oldAvg = avg(samples.slice(-20, -10).map((s) => s.latencyMs)); const newAvg = avg(samples.slice(-10).map((s) => s.latencyMs)); const degradationScore = oldAvg ? Math.max(0, Math.min(1, (newAvg - oldAvg) / oldAvg)) : 0; const failures = samples.slice(-20).filter((s) => !s.healthy).length; return { expectedLatencyMs: newAvg || 100, degradationScore, failureProbability: failures / Math.max(1, Math.min(20, samples.length)), stabilityTrend: degradationScore > 0.25 ? 'degrading' : degradationScore < -0.1 ? 'improving' : 'stable' }; }
  private maybeSwitch(best: ProviderScore): void { if (best.provider.id === this.activeProviderId) return; const current = this.rankProviders().find((ranked) => ranked.provider.id === this.activeProviderId); const failed = (this.failureStreak.get(this.activeProviderId ?? '') ?? 0) >= this.config.failover.failureThreshold; const cooldownOver = Date.now() - this.lastSwitchAt >= this.config.failover.cooldownMs; if ((failed || (cooldownOver && (!current || best.score - current.score >= this.config.minSwitchScoreDelta)))) { this.activeProviderId = best.provider.id; this.lastSwitchAt = Date.now(); this.recordEvent(failed ? 'failover.switch' : 'provider.switch', best.provider.id, `Switched to ${best.provider.name}`); } }
  private selectProviderForRule(rule?: DnsRule): DnsProvider | undefined { if (!rule) return undefined; if (['force-provider', 'prefer-provider', 'fallback-provider'].includes(rule.action) && rule.providerId) return this.providers.find((provider) => provider.id === rule.providerId); return undefined; }
  private recordEvent(type: string, providerId: string | undefined, message: string, metadata?: Record<string, unknown>): void { const event: DnsEngineEvent = { type, message, timestamp: new Date().toISOString(), ...(providerId === undefined ? {} : { providerId }), ...(metadata === undefined ? {} : { metadata }) }; this.events.push(event); this.emit('event', event); }
}
const avg = (values: number[]): number => values.length ? values.reduce((s, v) => s + v, 0) / values.length : 0;

export class SystemDnsManager { async apply(provider: DnsProvider, iface = 'default'): Promise<{ ok: boolean; rollback: () => Promise<void>; details: string }> { const previous = await this.snapshot(); const addresses = provider.addresses ?? []; if (addresses.length === 0) return { ok: false, rollback: async () => undefined, details: 'Provider has no addresses' }; try { await this.applyForPlatform(addresses, iface); return { ok: true, rollback: async () => { await this.restore(previous); }, details: `Applied ${provider.name}` }; } catch (error) { await this.restore(previous); return { ok: false, rollback: async () => undefined, details: error instanceof Error ? error.message : String(error) }; } } async flushCache(): Promise<string> { const p = platform(); const commands = p === 'win32' ? ['powershell.exe', '-NoProfile', '-Command', 'Clear-DnsClientCache'] : p === 'darwin' ? ['dscacheutil', '-flushcache'] : ['resolvectl', 'flush-caches']; const { stdout, stderr } = await execFileAsync(commands[0] ?? 'true', commands.slice(1)); return stdout || stderr || 'cache flushed'; } private async snapshot(): Promise<string> { try { const { stdout } = await execFileAsync('cat', ['/etc/resolv.conf']); return stdout; } catch { return ''; } } private async restore(_snapshot: string): Promise<void> { return undefined; } private async applyForPlatform(addresses: string[], iface: string): Promise<void> { const p = platform(); if (p === 'win32') await execFileAsync('powershell.exe', ['-NoProfile', '-Command', `Set-DnsClientServerAddress -InterfaceAlias '${iface}' -ServerAddresses ${addresses.join(',')}`]); else if (p === 'darwin') await execFileAsync('networksetup', ['-setdnsservers', iface, ...addresses]); else await execFileAsync('resolvectl', ['dns', iface, ...addresses]); } }

export class WorkerSupervisor { private readonly controllers = new Map<string, AbortController>(); start(name: string, intervalMs: number, task: (signal: AbortSignal) => Promise<void>): void { const controller = new AbortController(); this.controllers.set(name, controller); const run = async (): Promise<void> => { while (!controller.signal.aborted) { await task(controller.signal); await new Promise((resolve) => setTimeout(resolve, intervalMs)); } }; void run(); } async stop(): Promise<void> { for (const controller of this.controllers.values()) controller.abort(); this.controllers.clear(); } }
