import type { ProviderMetadata } from './index.js';

export type BuiltinProviderCatalogEntry = ProviderMetadata & {
  dnssec: boolean;
  region: 'IR' | 'global';
  discovery: 'curated' | 'iran-public-dns' | 'community-catalog';
};

const provider = (
  entry: BuiltinProviderCatalogEntry,
): BuiltinProviderCatalogEntry => entry;

/**
 * Extended public-resolver catalog.
 *
 * This catalog intentionally distinguishes resolver identity from runtime health:
 * membership here never makes a resolver preferred. Runtime probing and scoring
 * remain authoritative for selection.
 */
export const EXTENDED_PROVIDER_METADATA: BuiltinProviderCatalogEntry[] = [
  // Iranian / Iran-relevant public resolvers.
  provider({ id: 'shecan', name: 'Shecan', country: 'IR', homepage: 'https://shecan.ir/', endpoints: { ipv4: ['178.22.122.100', '185.51.200.2'], ipv6: [] }, tags: ['iran', 'regional', 'uncensored'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'shecan-2', name: 'Shecan Secondary Set', country: 'IR', homepage: 'https://shecan.ir/', endpoints: { ipv4: ['178.22.122.101', '185.51.200.1'], ipv6: [] }, tags: ['iran', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'begzar', name: 'Begzar', country: 'IR', homepage: 'https://begzar.ir/', endpoints: { ipv4: ['185.55.225.25', '185.55.226.26'], ipv6: [] }, tags: ['iran', 'regional', 'uncensored'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: '403', name: '403 Online', country: 'IR', homepage: 'https://403.online/', endpoints: { ipv4: ['10.202.10.202', '10.202.10.102'], ipv6: [] }, tags: ['iran', 'regional', 'uncensored'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'radar', name: 'Radar Game', country: 'IR', homepage: 'https://radar.game/', endpoints: { ipv4: ['10.202.10.10', '10.202.10.11'], ipv6: [] }, tags: ['iran', 'regional', 'gaming'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'electro', name: 'Electro', country: 'IR', homepage: 'https://electro.team/', endpoints: { ipv4: ['78.157.42.100', '78.157.42.101'], ipv6: [] }, tags: ['iran', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'shatel', name: 'Shatel', country: 'IR', homepage: 'https://shatel.ir/', endpoints: { ipv4: ['85.15.1.14', '85.15.1.15'], ipv6: [] }, tags: ['iran', 'isp', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'shelter', name: 'Shelter', country: 'IR', homepage: 'https://shelter.ir/', endpoints: { ipv4: ['78.157.60.6', '78.157.60.242'], ipv6: [] }, tags: ['iran', 'regional', 'gaming'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'shelter-2', name: 'Shelter Secondary Set', country: 'IR', homepage: 'https://shelter.ir/', endpoints: { ipv4: ['91.92.250.185', '91.92.244.233'], ipv6: [] }, tags: ['iran', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'beshkan', name: 'Beshkan', country: 'IR', homepage: 'https://beshkan.com/', endpoints: { ipv4: ['181.41.194.177', '181.41.194.186'], ipv6: [] }, tags: ['iran', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'nobarcloud', name: 'NobarCloud', country: 'IR', homepage: 'https://nobarcloud.ir/', endpoints: { ipv4: ['78.110.120.220', '78.110.120.200'], ipv6: [] }, tags: ['iran', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'dynx', name: 'DynX', country: 'IR', homepage: 'https://dynx.ir/', endpoints: { ipv4: ['193.24.103.1', '193.24.103.2'], ipv6: [] }, tags: ['iran', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'bertina', name: 'Bertina', country: 'IR', homepage: 'https://www.bertina.ir/', endpoints: { ipv4: ['193.186.32.32'], ipv6: [] }, tags: ['iran', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'hostiran', name: 'HostIran', country: 'IR', homepage: 'https://hostiran.net/', endpoints: { ipv4: ['172.29.0.100', '172.29.2.100'], ipv6: [] }, tags: ['iran', 'private', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'vanilla', name: 'Vanilla', country: 'IR', homepage: 'https://vanilla.ir/', endpoints: { ipv4: ['10.139.177.21', '10.139.177.22'], ipv6: [] }, tags: ['iran', 'private', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: '3dns', name: '3DNS', country: 'IR', homepage: 'https://3dns.ir/', endpoints: { ipv4: ['77.77.77.77', '77.77.77.78'], ipv6: [] }, tags: ['iran', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'tic', name: 'Telecommunication Infrastructure Company', country: 'IR', homepage: 'https://tic.ir/', endpoints: { ipv4: ['2.188.21.133', '217.218.155.155'], ipv6: [] }, tags: ['iran', 'isp', 'regional'], dnssec: true, region: 'IR', discovery: 'iran-public-dns' }),
  provider({ id: 'tci', name: 'Telecommunication Company of Iran', country: 'IR', homepage: 'https://tci.ir/', endpoints: { ipv4: ['5.200.200.200', '217.219.72.194'], ipv6: [] }, tags: ['iran', 'isp', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'ipm', name: 'Institute for Research in Fundamental Sciences', country: 'IR', homepage: 'https://ipm.ac.ir/', endpoints: { ipv4: ['194.225.152.10', '194.225.152.12', '194.225.152.13'], ipv6: [] }, tags: ['iran', 'academic', 'regional'], dnssec: true, region: 'IR', discovery: 'iran-public-dns' }),
  provider({ id: 'asiatech', name: 'Asiatech', country: 'IR', homepage: 'https://asiatech.ir/', endpoints: { ipv4: ['185.98.113.113', '185.98.113.114'], ipv6: [] }, tags: ['iran', 'isp', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'derak-cloud', name: 'Derak Cloud', country: 'IR', homepage: 'https://derak.cloud/', endpoints: { ipv4: ['193.151.128.100', '193.151.128.200'], ipv6: [] }, tags: ['iran', 'cloud', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'irnic', name: 'IRNIC', country: 'IR', homepage: 'https://www.nic.ir/', endpoints: { ipv4: ['193.189.123.2', '193.189.122.83'], ipv6: [] }, tags: ['iran', 'registry', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'pishgaman', name: 'Pishgaman', country: 'IR', homepage: 'https://pishgaman.net/', endpoints: { ipv4: ['5.202.100.100', '5.202.100.101'], ipv6: [] }, tags: ['iran', 'isp', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'rightel', name: 'Rightel', country: 'IR', homepage: 'https://rightel.ir/', endpoints: { ipv4: ['91.239.100.100', '89.233.43.71'], ipv6: [] }, tags: ['iran', 'mobile', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'irancell', name: 'Irancell', country: 'IR', homepage: 'https://irancell.ir/', endpoints: { ipv4: ['74.82.42.42'], ipv6: [] }, tags: ['iran', 'mobile', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'mci', name: 'Hamrah Aval', country: 'IR', homepage: 'https://mci.ir/', endpoints: { ipv4: ['208.67.220.200', '208.67.222.222'], ipv6: [] }, tags: ['iran', 'mobile', 'regional'], dnssec: false, region: 'IR', discovery: 'community-catalog' }),
  provider({ id: 'shahrad', name: 'Sefroyek Pardaz / Shahrad', country: 'IR', homepage: 'https://shahrad.net/', endpoints: { ipv4: ['185.51.200.10', '185.51.200.50'], ipv6: [] }, tags: ['iran', 'regional'], dnssec: false, region: 'IR', discovery: 'iran-public-dns' }),
  provider({ id: 'parsonline', name: 'ParsOnline', country: 'IR', homepage: 'https://parsonline.com/', endpoints: { ipv4: ['91.99.101.12'], ipv6: [] }, tags: ['iran', 'isp', 'regional'], dnssec: false, region: 'IR', discovery: 'iran-public-dns' }),
  provider({ id: 'irost', name: 'Iranian Research Organization for Science and Technology', country: 'IR', homepage: 'https://irost.org/', endpoints: { ipv4: ['213.176.123.5'], ipv6: [] }, tags: ['iran', 'academic', 'regional'], dnssec: false, region: 'IR', discovery: 'iran-public-dns' }),
  provider({ id: 'tums', name: 'Tehran University of Medical Sciences', country: 'IR', homepage: 'https://tums.ac.ir/', endpoints: { ipv4: ['194.225.62.80'], ipv6: [] }, tags: ['iran', 'academic', 'regional'], dnssec: true, region: 'IR', discovery: 'iran-public-dns' }),
  provider({ id: 'arvancloud', name: 'ArvanCloud', country: 'IR', homepage: 'https://www.arvancloud.ir/', endpoints: { ipv4: ['185.97.117.187', '185.231.182.126'], ipv6: [] }, tags: ['iran', 'cloud', 'regional'], dnssec: false, region: 'IR', discovery: 'iran-public-dns' }),
  provider({ id: 'farabordadeh', name: 'Farabord Dadeh Haye Iranian', country: 'IR', homepage: 'https://www.farabord.ir/', endpoints: { ipv4: ['81.91.144.116'], ipv6: [] }, tags: ['iran', 'regional'], dnssec: false, region: 'IR', discovery: 'iran-public-dns' }),
  provider({ id: 'parvazsys', name: 'Parvaz System', country: 'IR', homepage: 'https://parvazsys.com/', endpoints: { ipv4: ['185.161.112.33', '185.161.112.34'], ipv6: [] }, tags: ['iran', 'regional'], dnssec: false, region: 'IR', discovery: 'iran-public-dns' }),
  provider({ id: 'hesabgar', name: 'Hesabgar Pardaz Gharb', country: 'IR', homepage: 'https://hesabgar.com/', endpoints: { ipv4: ['185.47.48.26'], ipv6: [] }, tags: ['iran', 'regional'], dnssec: false, region: 'IR', discovery: 'iran-public-dns' }),

  // Global public resolvers from current public-resolver catalogs and operator lists.
  provider({ id: 'mullvad', name: 'Mullvad DNS', country: 'SE', homepage: 'https://mullvad.net/en/help/dns-over-https-and-dns-over-tls/', endpoints: { ipv4: ['194.242.2.2'], ipv6: ['2a07:e340::2'], doh: 'https://dns.mullvad.net/dns-query', dot: 'dns.mullvad.net' }, tags: ['privacy', 'security'], dnssec: true, region: 'global', discovery: 'curated' }),
  provider({ id: 'wikimedia', name: 'Wikimedia DNS', country: 'US', homepage: 'https://meta.wikimedia.org/wiki/Wikimedia_DNS', endpoints: { ipv4: ['185.71.138.138'], ipv6: ['2001:67c:930::1'], doh: 'https://wikimedia-dns.org/dns-query', dot: 'wikimedia-dns.org' }, tags: ['privacy', 'public'], dnssec: true, region: 'global', discovery: 'curated' }),
  provider({ id: 'dns4eu', name: 'DNS4EU', country: 'EU', homepage: 'https://www.joindns4.eu/', endpoints: { ipv4: ['86.54.11.1', '86.54.11.100'], ipv6: [], doh: 'https://protective.joindns4.eu/dns-query' }, tags: ['europe', 'security', 'public'], dnssec: true, region: 'global', discovery: 'curated' }),
  provider({ id: 'uncensoreddns', name: 'UncensoredDNS', country: 'DK', homepage: 'https://blog.uncensoreddns.org/', endpoints: { ipv4: ['91.239.100.100', '89.233.43.71'], ipv6: ['2001:67c:28a4::', '2a01:3a0:53:53::'], doh: 'https://anycast.uncensoreddns.org/dns-query', dot: 'anycast.uncensoreddns.org' }, tags: ['privacy', 'uncensored'], dnssec: true, region: 'global', discovery: 'curated' }),
  provider({ id: 'quad101', name: 'Quad101 / TWNIC', country: 'TW', homepage: 'https://twnic.tw/', endpoints: { ipv4: ['101.101.101.101', '101.102.103.104'], ipv6: ['2001:de4::101', '2001:de4::102'], doh: 'https://dns.twnic.tw/dns-query', dot: '101.101.101.101' }, tags: ['asia', 'public'], dnssec: true, region: 'global', discovery: 'curated' }),
  provider({ id: 'alidns', name: 'AliDNS', country: 'CN', homepage: 'https://www.alidns.com/', endpoints: { ipv4: ['223.5.5.5', '223.6.6.6'], ipv6: ['2400:3200::1', '2400:3200:baba::1'], doh: 'https://dns.alidns.com/dns-query', dot: 'dns.alidns.com' }, tags: ['asia', 'public'], dnssec: true, region: 'global', discovery: 'curated' }),
  provider({ id: 'dnspod', name: 'DNSPod Public DNS', country: 'CN', homepage: 'https://www.dnspod.cn/', endpoints: { ipv4: ['119.29.29.29', '119.28.28.28'], ipv6: ['2402:4e00::', '2402:4e00:1::'], doh: 'https://doh.pub/dns-query', dot: 'dot.pub' }, tags: ['asia', 'public'], dnssec: true, region: 'global', discovery: 'curated' }),
  provider({ id: 'baidu', name: 'Baidu Public DNS', country: 'CN', homepage: 'https://dudns.baidu.com/', endpoints: { ipv4: ['180.76.76.76'], ipv6: ['2400:da00::6666'] }, tags: ['asia', 'public'], dnssec: false, region: 'global', discovery: 'curated' }),
  provider({ id: '114dns', name: '114DNS', country: 'CN', homepage: 'https://www.114dns.com/', endpoints: { ipv4: ['114.114.114.114', '114.114.115.115'], ipv6: [] }, tags: ['asia', 'public'], dnssec: false, region: 'global', discovery: 'curated' }),
  provider({ id: 'onedns', name: 'OneDNS', country: 'CN', homepage: 'https://www.onedns.net/', endpoints: { ipv4: ['117.50.10.10', '52.80.52.52'], ipv6: ['2400:7fc0:849e:200::8', '2404:c2c0:85d8:901::8'], doh: 'https://doh.onedns.net/dns-query', dot: 'dot.onedns.net' }, tags: ['asia', 'privacy'], dnssec: true, region: 'global', discovery: 'curated' }),
  provider({ id: 'cnnicsdns', name: 'CNNIC SDNS', country: 'CN', homepage: 'https://www.sdns.cn/', endpoints: { ipv4: ['1.2.4.8', '210.2.4.8'], ipv6: [] }, tags: ['asia', 'public'], dnssec: false, region: 'global', discovery: 'curated' }),
  provider({ id: '360dns', name: '360 DNS', country: 'CN', homepage: 'https://www.360.cn/', endpoints: { ipv4: ['101.226.4.6', '218.30.118.6'], ipv6: [], doh: 'https://doh.360.cn/dns-query', dot: 'dot.360.cn' }, tags: ['asia', 'security'], dnssec: false, region: 'global', discovery: 'curated' }),
  provider({ id: 'volcengine', name: 'Volcengine TrafficRoute DNS', country: 'CN', homepage: 'https://www.volcengine.com/', endpoints: { ipv4: ['180.184.1.1', '180.184.2.2'], ipv6: [] }, tags: ['asia', 'public'], dnssec: false, region: 'global', discovery: 'curated' }),
  provider({ id: 'yandex', name: 'Yandex DNS', country: 'RU', homepage: 'https://dns.yandex.com/', endpoints: { ipv4: ['77.88.8.8', '77.88.8.1'], ipv6: ['2a02:6b8::feed:0ff', '2a02:6b8:0:1::feed:0ff'], dot: 'common.dot.dns.yandex.net' }, tags: ['security', 'public'], dnssec: true, region: 'global', discovery: 'curated' }),
  provider({ id: 'verisign', name: 'Verisign Public DNS', country: 'US', homepage: 'https://www.verisign.com/en_US/security-services/public-dns/', endpoints: { ipv4: ['64.6.64.6', '64.6.65.6'], ipv6: ['2620:74:1b::1:1', '2620:74:1c::2:2'] }, tags: ['security', 'public'], dnssec: true, region: 'global', discovery: 'curated' }),
  provider({ id: 'comodo', name: 'Comodo Secure DNS', country: 'US', homepage: 'https://www.comodo.com/secure-dns/', endpoints: { ipv4: ['8.26.56.26', '8.20.247.20'], ipv6: [] }, tags: ['security', 'public'], dnssec: true, region: 'global', discovery: 'community-catalog' }),
  provider({ id: 'alternatedns', name: 'Alternate DNS', country: 'US', homepage: 'https://alternate-dns.com/', endpoints: { ipv4: ['76.76.19.19', '76.223.122.150'], ipv6: ['2602:fcbc::ad', '2602:fcbc:2::ad'] }, tags: ['privacy', 'public'], dnssec: true, region: 'global', discovery: 'community-catalog' }),
  provider({ id: 'dnswatch', name: 'DNS.Watch', country: 'DE', homepage: 'https://dns.watch/', endpoints: { ipv4: ['84.200.69.80', '84.200.70.40'], ipv6: ['2001:1608:10:25::1c04:b12f', '2001:1608:10:25::9249:d69b'] }, tags: ['privacy', 'public'], dnssec: true, region: 'global', discovery: 'community-catalog' }),
  provider({ id: 'freenom-world', name: 'Freenom World', country: 'NL', homepage: 'https://www.freenom.world/', endpoints: { ipv4: ['80.80.80.80', '80.80.81.81'], ipv6: ['2001:4860:4860::8888', '2001:4860:4860::8844'] }, tags: ['public'], dnssec: false, region: 'global', discovery: 'community-catalog' }),
  provider({ id: 'he', name: 'Hurricane Electric', country: 'US', homepage: 'https://dns.he.net/', endpoints: { ipv4: ['74.82.42.42'], ipv6: ['2001:470:20::2'] }, tags: ['public', 'ipv6'], dnssec: true, region: 'global', discovery: 'community-catalog' }),
  provider({ id: 'level3', name: 'Level 3 Public DNS', country: 'US', homepage: 'https://www.lumen.com/', endpoints: { ipv4: ['4.2.2.1', '4.2.2.2'], ipv6: [] }, tags: ['public'], dnssec: false, region: 'global', discovery: 'community-catalog' }),
  provider({ id: 'neustar', name: 'Neustar UltraRecursive', country: 'US', homepage: 'https://www.vercaradns.com/', endpoints: { ipv4: ['64.6.64.6', '64.6.65.6'], ipv6: [] }, tags: ['security', 'public'], dnssec: true, region: 'global', discovery: 'community-catalog' }),
  provider({ id: 'opennic', name: 'OpenNIC', homepage: 'https://www.opennic.org/', endpoints: { ipv4: ['147.182.243.83'], ipv6: [] }, tags: ['community', 'public'], dnssec: false, region: 'global', discovery: 'community-catalog' }),
  provider({ id: 'greenteamdns', name: 'GreenTeamDNS', country: 'US', homepage: 'https://www.greenteamdns.com/', endpoints: { ipv4: ['81.218.119.11', '209.88.198.133'], ipv6: [] }, tags: ['filtering', 'security'], dnssec: false, region: 'global', discovery: 'community-catalog' }),
  provider({ id: 'safedns', name: 'SafeDNS', country: 'US', homepage: 'https://www.safedns.com/', endpoints: { ipv4: ['195.46.39.39', '195.46.39.40'], ipv6: [] }, tags: ['filtering', 'security'], dnssec: true, region: 'global', discovery: 'community-catalog' }),
  provider({ id: 'freedns', name: 'FreeDNS', country: 'US', homepage: 'https://freedns.controld.com/', endpoints: { ipv4: ['37.235.1.174', '37.235.1.177'], ipv6: [] }, tags: ['public'], dnssec: false, region: 'global', discovery: 'community-catalog' }),
  provider({ id: 'smartviper', name: 'SmartViper', country: 'US', homepage: 'https://www.smartviper.com/', endpoints: { ipv4: ['208.76.50.50', '208.76.51.51'], ipv6: [] }, tags: ['public'], dnssec: false, region: 'global', discovery: 'community-catalog' }),
  provider({ id: 'windscribe', name: 'Windscribe DNS', country: 'CA', homepage: 'https://windscribe.com/', endpoints: { ipv4: ['76.76.2.0', '76.76.2.3'], ipv6: [] }, tags: ['privacy', 'public'], dnssec: true, region: 'global', discovery: 'community-catalog' }),
];
