import { randomUUID } from 'node:crypto';
import { readdir } from 'node:fs/promises';
import { join } from 'node:path';
import type { AppConfig } from '@irp/config';
import type { Logger } from '@irp/logger';
import { createBuiltinProviders, type BenchmarkSample, type DnsProvider, type DnsQuestion } from '@irp/dns';

export interface Lifecycle { start(): Promise<void>; stop(): Promise<void>; }
export type RuntimeState = 'created' | 'starting' | 'running' | 'stopping' | 'stopped';
export type EventType = 'ProviderHealthy' | 'ProviderUnhealthy' | 'ProviderRecovered' | 'ConfigurationReloaded' | 'NetworkChanged' | 'ConnectivityLost' | 'ConnectivityRestored' | 'BenchmarkCompleted';
export interface RuntimeEvent<T = unknown> { id: string; type: EventType; timestamp: string; payload: T; }
export type EventSubscriber = (event: RuntimeEvent) => Promise<void> | void;
export interface Plugin extends Lifecycle { id: string; install?(container: Container): Promise<void> | void; initialize?(context: RuntimeContext): Promise<void> | void; unload?(): Promise<void> | void; }
export interface RuntimeContext { config: AppConfig; logger: Logger; container: Container; events: EventBus; }

export class Container { private readonly services = new Map<string, unknown>(); register<T>(token: string, service: T): void { this.services.set(token, service); } resolve<T>(token: string): T { const service = this.services.get(token); if (service === undefined) throw new Error(`Service not registered: ${token}`); return service as T; } has(token: string): boolean { return this.services.has(token); } }
export class EventBus { private readonly subscribers = new Map<EventType | '*', Set<EventSubscriber>>(); private readonly history: RuntimeEvent[] = []; subscribe(type: EventType | '*', subscriber: EventSubscriber): () => void { const set = this.subscribers.get(type) ?? new Set<EventSubscriber>(); set.add(subscriber); this.subscribers.set(type, set); return () => set.delete(subscriber); } async publish<T>(type: EventType, payload: T): Promise<RuntimeEvent<T>> { const event = { id: randomUUID(), type, timestamp: new Date().toISOString(), payload }; this.history.push(event); await Promise.all([...this.subscribers.get(type) ?? [], ...this.subscribers.get('*') ?? []].map((s) => s(event))); return event; } snapshot(): RuntimeEvent[] { return [...this.history.slice(-500)]; } }

export interface JobOptions { id: string; intervalMs?: number; runAt?: Date; retry?: { attempts: number; baseDelayMs: number; maxDelayMs: number; jitterRatio: number }; }
export class Scheduler implements Lifecycle { private readonly timers = new Map<string, NodeJS.Timeout>(); private stopping = false; constructor(private readonly logger?: Logger) {} schedule(options: JobOptions, job: () => Promise<void> | void): () => void { const run = async (attempt = 0): Promise<void> => { if (this.stopping) return; const started = Date.now(); try { await job(); this.logger?.debug('scheduler job completed', { id: options.id, latencyMs: Date.now() - started }); } catch (error) { const retry = options.retry; if (retry && attempt < retry.attempts) { const backoff = Math.min(retry.maxDelayMs, retry.baseDelayMs * 2 ** attempt); const jitter = backoff * retry.jitterRatio * Math.random(); this.timers.set(options.id, setTimeout(() => void run(attempt + 1), backoff + jitter)); return; } this.logger?.error('scheduler job failed', { id: options.id, error: error instanceof Error ? error.message : 'unknown' }); } if (options.intervalMs && !this.stopping) this.timers.set(options.id, setTimeout(() => void run(0), options.intervalMs)); }; const delay = Math.max(0, (options.runAt?.getTime() ?? Date.now()) - Date.now()); this.timers.set(options.id, setTimeout(() => void run(), delay)); return () => this.cancel(options.id); } cancel(id: string): void { const timer = this.timers.get(id); if (timer) clearTimeout(timer); this.timers.delete(id); } async start(): Promise<void> { this.stopping = false; } async stop(): Promise<void> { this.stopping = true; for (const id of this.timers.keys()) this.cancel(id); } }

export interface RollingStats { count: number; successes: number; failures: number; packetLoss: number; timeoutRate: number; jitterMs: number; averageResponseTimeMs: number; availability: number; successRatio: number; lastLatencyMs?: number; }
export class BenchmarkEngine { private readonly samples = new Map<string, BenchmarkSample[]>(); constructor(private readonly events: EventBus, private readonly maxSamples = 200) {} async run(providers: DnsProvider[], question: DnsQuestion = { name: 'example.com', recordType: 'A' }): Promise<BenchmarkSample[]> { const results = await Promise.all(providers.map(async (provider) => { const started = performance.now(); try { await provider.resolve(question, { timeoutMs: provider.config.timeoutMs }); return { providerId: provider.id, latencyMs: performance.now() - started, success: true, timedOut: false, timestamp: new Date().toISOString() }; } catch (error) { return { providerId: provider.id, latencyMs: performance.now() - started, success: false, timedOut: error instanceof Error && error.message.toLowerCase().includes('timeout'), error: error instanceof Error ? error.message : 'unknown', timestamp: new Date().toISOString() }; } })); for (const sample of results) this.record(sample); await this.events.publish('BenchmarkCompleted', { results }); return results; } record(sample: BenchmarkSample): void { const list = this.samples.get(sample.providerId) ?? []; list.push(sample); this.samples.set(sample.providerId, list.slice(-this.maxSamples)); } stats(providerId: string): RollingStats { const list = this.samples.get(providerId) ?? []; const successes = list.filter((s) => s.success); const latencies = successes.map((s) => s.latencyMs); const average = latencies.reduce((a, b) => a + b, 0) / (latencies.length || 1); const jitter = latencies.reduce((a, b) => a + Math.abs(b - average), 0) / (latencies.length || 1); return { count: list.length, successes: successes.length, failures: list.length - successes.length, packetLoss: list.length ? (list.length - successes.length) / list.length : 0, timeoutRate: list.length ? list.filter((s) => s.timedOut).length / list.length : 0, jitterMs: jitter, averageResponseTimeMs: average, availability: list.length ? successes.length / list.length : 0, successRatio: list.length ? successes.length / list.length : 0, lastLatencyMs: latencies.at(-1) }; } snapshot(): Record<string, RollingStats> { return Object.fromEntries([...this.samples.keys()].map((id) => [id, this.stats(id)])); } }
export class HealthScorer { score(provider: DnsProvider, stats: RollingStats): number { const latency = Math.max(0, 40 - Math.min(40, stats.averageResponseTimeMs / 10)); const reliability = (1 - stats.packetLoss) * 25 + (1 - stats.timeoutRate) * 15 + stats.successRatio * 10; const support = (provider.supportsDNSSEC() ? 4 : 0) + (provider.supportsDoH() ? 3 : 0) + (provider.supportsDoT() ? 3 : 0); const stability = Math.max(0, 10 - stats.jitterMs / 20); return Math.round(Math.max(0, Math.min(100, latency + reliability + support + stability))); } preferred(providers: DnsProvider[], stats: BenchmarkEngine): DnsProvider | undefined { return [...providers].sort((a, b) => this.score(b, stats.stats(b.id)) - this.score(a, stats.stats(a.id)))[0]; } }

export class PluginLoader { constructor(private readonly directory: string, private readonly logger: Logger) {} async discover(): Promise<string[]> { try { return (await readdir(this.directory, { withFileTypes: true })).filter((d) => d.isDirectory()).map((d) => join(this.directory, d.name, 'index.js')); } catch { return []; } } async load(_context: RuntimeContext): Promise<Plugin[]> { this.logger.info('plugin discovery completed', { directory: this.directory, plugins: 0 }); return []; } }
export class Application implements Lifecycle { private readonly plugins: Plugin[] = []; public readonly events = new EventBus(); public readonly scheduler = new Scheduler(this.logger); public readonly providers = createBuiltinProviders(); public readonly benchmark = new BenchmarkEngine(this.events); public readonly scorer = new HealthScorer(); public state: RuntimeState = 'created'; constructor(public config: AppConfig, public readonly logger: Logger, public readonly container = new Container()) { container.register('events', this.events); container.register('scheduler', this.scheduler); container.register('providers', this.providers); container.register('benchmark', this.benchmark); } use(plugin: Plugin): void { this.plugins.push(plugin); } async start(): Promise<void> { if (this.state === 'running' || this.state === 'starting') return; this.state = 'starting'; this.logger.info('application starting', { providers: this.providers.map((p) => p.id), plugins: this.plugins.map((p) => p.id) }); await this.scheduler.start(); for (const plugin of this.plugins) { await plugin.install?.(this.container); await plugin.initialize?.({ config: this.config, logger: this.logger, container: this.container, events: this.events }); await plugin.start(); } this.scheduler.schedule({ id: 'benchmark.providers', intervalMs: 60_000, retry: { attempts: 2, baseDelayMs: 500, maxDelayMs: 5_000, jitterRatio: 0.2 } }, () => this.benchmark.run(this.providers)); this.state = 'running'; } async stop(): Promise<void> { if (this.state === 'stopped' || this.state === 'stopping') return; this.state = 'stopping'; await this.scheduler.stop(); for (const plugin of [...this.plugins].reverse()) { await plugin.stop(); await plugin.unload?.(); } this.state = 'stopped'; this.logger.info('application stopped'); } async reload(config: AppConfig): Promise<void> { this.config = config; await this.events.publish('ConfigurationReloaded', { environment: config.app.environment }); } }
