import { randomUUID } from 'node:crypto';
import type { AppConfig } from '@irp/config';
import type { Logger } from '@irp/logger';

export interface Lifecycle { start(): Promise<void>; stop(): Promise<void>; }
export interface Plugin extends Lifecycle { id: string; install?(container: Container): Promise<void> | void; unload?(): Promise<void> | void; }
export type Token<T> = string & { readonly __type?: T };
export class Container { private readonly services = new Map<string, unknown>(); register<T>(token: Token<T> | string, service: T): void { this.services.set(token, service); } resolve<T>(token: Token<T> | string): T { const service = this.services.get(token); if (service === undefined) throw new Error(`Service not registered: ${token}`); return service as T; } has(token: Token<unknown> | string): boolean { return this.services.has(token); } }
export class AppError extends Error { constructor(public readonly code: string, message: string, public readonly statusCode = 500, public readonly details?: Record<string, unknown>) { super(message); } }
export class ValidationAppError extends AppError { constructor(message: string, details?: Record<string, unknown>) { super('VALIDATION_ERROR', message, 400, details); } }
export class UnauthorizedAppError extends AppError { constructor(message = 'Authentication is required') { super('UNAUTHORIZED', message, 401); } }
export class ForbiddenAppError extends AppError { constructor(message = 'Insufficient permissions') { super('FORBIDDEN', message, 403); } }
export class ConflictAppError extends AppError { constructor(message: string, details?: Record<string, unknown>) { super('CONFLICT', message, 409, details); } }
export class NotFoundAppError extends AppError { constructor(resource: string) { super('NOT_FOUND', `${resource} was not found`, 404); } }
export const mapErrorToHttp = (error: unknown): { statusCode: number; body: { success: false; error: { code: string; message: string; details?: Record<string, unknown> } } } => error instanceof AppError ? { statusCode: error.statusCode, body: { success: false, error: { code: error.code, message: error.message, ...(error.details ? { details: error.details } : {}) } } } : { statusCode: 500, body: { success: false, error: { code: 'INTERNAL_ERROR', message: 'An unexpected error occurred' } } };
export interface DomainEvent<T = unknown> { id: string; type: string; aggregateId: string; occurredAt: Date; payload: T; metadata?: Record<string, string>; }
export type EventHandler<T extends DomainEvent = DomainEvent> = (event: T) => Promise<void> | void;
export class EventBus { private readonly handlers = new Map<string, Set<EventHandler>>(); private readonly history: DomainEvent[] = []; subscribe<T extends DomainEvent>(type: T['type'] | '*', handler: EventHandler<T>): () => void { const set = this.handlers.get(type) ?? new Set<EventHandler>(); set.add(handler as EventHandler); this.handlers.set(type, set); return () => set.delete(handler as EventHandler); } async publish<T extends DomainEvent>(event: T): Promise<void>; async publish(type: string, payload: unknown): Promise<void>; async publish(eventOrType: DomainEvent | string, payload?: unknown): Promise<void> { const event = typeof eventOrType === 'string' ? createDomainEvent(eventOrType, eventOrType, payload) : eventOrType; this.history.push(event); const handlers = [...(this.handlers.get(event.type) ?? []), ...(this.handlers.get('*') ?? [])]; await Promise.all(handlers.map((handler) => handler(event))); } snapshot(): DomainEvent[] { return this.history.slice(-500); } }
export const createDomainEvent = <T>(type: string, aggregateId: string, payload: T): DomainEvent<T> => ({ id: randomUUID(), type, aggregateId, payload, occurredAt: new Date() });
export interface QueueMessage<T = unknown> { id: string; name: string; payload: T; attempts: number; enqueuedAt: Date; }
export class Cache<T = unknown> { private readonly values = new Map<string, { value: T; expiresAt: number }>(); set(key: string, value: T, ttlMs: number): void { this.values.set(key, { value, expiresAt: Date.now() + ttlMs }); } get(key: string): T | null { const item = this.values.get(key); if (!item) return null; if (item.expiresAt <= Date.now()) { this.values.delete(key); return null; } return item.value; } delete(key: string): void { this.values.delete(key); } size(): number { return this.values.size; } }
export class Application implements Lifecycle { private readonly plugins: Plugin[] = []; public state: 'created' | 'running' | 'stopped' = 'created'; public readonly events = new EventBus(); public readonly scheduler: Scheduler; public readonly benchmark = new BenchmarkEngine(); public readonly scorer = new HealthScorer(); public readonly providers = [{ id: 'cloudflare', name: 'Cloudflare' }, { id: 'google', name: 'Google' }]; constructor(public config: AppConfig, public readonly logger: Logger, public readonly container = new Container()) { this.scheduler = new Scheduler(logger); } use(plugin: Plugin): void { this.plugins.push(plugin); } async start(): Promise<void> { if (this.state === 'running') return; for (const plugin of this.plugins) { await plugin.install?.(this.container); await plugin.start(); } this.state = 'running'; this.logger.info('application started', { plugins: this.plugins.map((p) => p.id) }); } async stop(): Promise<void> { if (this.state === 'stopped') return; await this.scheduler.stop(); for (const plugin of [...this.plugins].reverse()) { await plugin.stop(); await plugin.unload?.(); } this.state = 'stopped'; this.logger.info('application stopped'); } async reload(config: AppConfig): Promise<void> { this.config = config; await this.events.publish(createDomainEvent('ConfigurationReloaded', 'platform', { environment: config.app.environment })); } }

export interface JobOptions { id: string; intervalMs?: number; runAt?: Date; retry?: { attempts: number; baseDelayMs: number; maxDelayMs: number; jitterRatio: number }; }
export class Scheduler implements Lifecycle { private readonly timers = new Map<string, NodeJS.Timeout>(); private stopping = false; constructor(private readonly logger?: Logger) {} schedule(options: JobOptions, job: () => Promise<void> | void): () => void { const run = async (): Promise<void> => { if (this.stopping) return; try { await job(); } catch (error) { this.logger?.error('scheduler job failed', { id: options.id, error: error instanceof Error ? error.message : 'unknown' }); } if (options.intervalMs && !this.stopping) this.timers.set(options.id, setTimeout(() => void run(), options.intervalMs)); }; const delay = Math.max(0, (options.runAt?.getTime() ?? Date.now()) - Date.now()); this.timers.set(options.id, setTimeout(() => void run(), delay)); return () => this.cancel(options.id); } cancel(id: string): void { const timer = this.timers.get(id); if (timer) clearTimeout(timer); this.timers.delete(id); } async start(): Promise<void> { this.stopping = false; } async stop(): Promise<void> { this.stopping = true; for (const id of [...this.timers.keys()]) this.cancel(id); } }
export interface BenchmarkSample { providerId: string; latencyMs: number; success: boolean; timedOut: boolean; timestamp: string; }
export interface RollingStats { count: number; successes: number; failures: number; averageResponseTimeMs: number; availability: number; }
export class BenchmarkEngine { private readonly samples = new Map<string, BenchmarkSample[]>(); record(sample: BenchmarkSample): void { const list = this.samples.get(sample.providerId) ?? []; list.push(sample); this.samples.set(sample.providerId, list.slice(-200)); } stats(providerId: string): RollingStats { const samples = this.samples.get(providerId) ?? []; const successes = samples.filter((s) => s.success).length; const avg = samples.length ? samples.reduce((sum, s) => sum + s.latencyMs, 0) / samples.length : 0; return { count: samples.length, successes, failures: samples.length - successes, averageResponseTimeMs: avg, availability: samples.length ? successes / samples.length : 1 }; } snapshot(): BenchmarkSample[] { return [...this.samples.values()].flat(); } }
export interface ScoredProvider { id: string; name: string; }
export class HealthScorer { score(_provider: ScoredProvider, stats: RollingStats): number { const latencyScore = Math.max(0, 100 - stats.averageResponseTimeMs); return Math.round((stats.availability * 100 * 0.7) + (latencyScore * 0.3)); } }
